In [4]:
import numpy as np

In [5]:
arr=np.random.randint(0,100,size=(5,4))
print(f"Array:\n{arr}\n")

Array:
[[22 33 73 41]
 [52 72  6 22]
 [82 80 14 40]
 [69 42 36 67]
 [37  1 82 71]]



In [12]:
arr1, arr2=np.array_split(arr,2);
print(f"First array after splitting:\n{arr1}\n")
print(f"Second array after splitting:\n{arr2}\n")

First array after splitting:
[[22 33 73 41]
 [52 72  6 22]
 [82 80 14 40]]

Second array after splitting:
[[69 42 36 67]
 [37  1 82 71]]



In [16]:
searchEl=(arr1==6);
print(f"Try to find 6 in first spliited half of array\n{searchEl}\n")
count=np.sum(searchEl)
print(f"Found elements: {count}\n")

Try to find 6 in first spliited half of array
[[False False False False]
 [False False  True False]
 [False False False False]]

Found elements: 1



In [18]:
import pandas as pd

In [20]:
series=pd.Series(np.random.randint(0,100, size=10));
print(f"Series Object\n{series}\n");

Series Object
0    16
1    72
2    32
3    29
4    78
5    36
6     0
7    49
8    26
9    77
dtype: int32



In [21]:
print(f"Elements sum: {series.sum()}");
print(f"Elements average: {series.mean()}");

Elements sum: 415
Elements average: 41.5


In [23]:
df=pd.DataFrame(np.random.randint(0,100, size=(4,4)), columns=list("abcd"));
print(f"DataFrame:\n{df}\n")

DataFrame:
    a   b   c   d
0  54  20  71  35
1  81  35  36  79
2  41  88  69  59
3  78  71  64  75



In [24]:
df=df.drop(0)
print(f"DataFrame after row removing:\n{df}\n")

DataFrame after row removing:
    a   b   c   d
1  81  35  36  79
2  41  88  69  59
3  78  71  64  75



In [25]:
df=df.drop(columns='a')
print(f"DataFrame after column removing:\n{df}\n")

DataFrame after column removing:
    b   c   d
1  35  36  79
2  88  69  59
3  71  64  75



In [27]:
print(f"DataFrame size: {df.shape}");

DataFrame size: (3, 3)


In [29]:
searchInDf=(df==75)
print(f"Try to find element 75 in Dataframe:\n{searchInDf}\n");

Try to find element 75 in Dataframe:
       b      c      d
1  False  False  False
2  False  False  False
3  False  False   True

